env = {
    'FLASK_ENV': 'development',
    'BIN_DIR': '/home/runner/work/sirendb/sirendb/bin',
    # 'GEO_BUILD_DIR': '/home/runner/work/sirendb/sirendb/geoapp/build',
    'IMAGE_STORE_PATH': '/home/runner/work/sirendb/sirendb/images',
}

contents = '# generated by .github/workflows/build_env.py\n'

for key, value in env.items():
    contents += f'{key} = {value}\n'

with open('etc/config.yml', 'w') as fp:
    fp.write(contents)
