name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
          architecture: 'x64'

      - name: Update pip, wheel, and setuptools
        run: pip install -U pip wheel setuptools

      - name: Setup the virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Run tests
        run: |
          dbversion=$(createdb --version)
          pgversion=$(python -c "import re; print(re.compile(r'createdb \(\S+\ ([^\.]+)').match('${dbversion}').groups()[0])")
          export PATH=/usr/lib/postgresql/$pgversion/bin:$PATH

          which pg_ctl
          which createdb
          which pg_config

          coverage run -m pytest
          coverage report
